sudo: required
services:
    docker

before_install:
    - docker build -t alenaliapko/react-test -f ./client/Dockerfile.dev

script:
    - docker run alenaliapko/react-test npm test -- --coverage

after_success:
    - docker build -t alenaliapko/multi-client ./client
    - docker build -t alenaliapko/multi-nginx ./nginx
    - docker build -t alenaliapko/multi-server ./server
    - docker build -t alenaliapko/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push alenaliapko/multi-client
    - docker push alenaliapko/multi-nginx
    - docker push alenaliapko/multi-server
    - docker push alenaliapko/multi-worker